/* Based on C header file by STMicroelectronics
 *
 *******************************************************************************
 *
 * <h2><center>&copy; COPYRIGHT 2013 STMicroelectronics</center></h2>
 *
 * Licensed under MCD-ST Liberty SW License Agreement V2, (the "License");
 * You may not use this file except in compliance with the License.
 * You may obtain a copy of the License at:
 *
 *        http://www.st.com/software_license_agreement_liberty_v2
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *******************************************************************************
 */

.equ RCC_AHB1Periph_GPIOA,        0x00000001
.equ RCC_AHB1Periph_GPIOB,        0x00000002
.equ RCC_AHB1Periph_GPIOC,        0x00000004
.equ RCC_AHB1Periph_GPIOD,        0x00000008
.equ RCC_AHB1Periph_GPIOE,        0x00000010
.equ RCC_AHB1Periph_GPIOF,        0x00000020
.equ RCC_AHB1Periph_GPIOG,        0x00000040
.equ RCC_AHB1Periph_GPIOH,        0x00000080
.equ RCC_AHB1Periph_GPIOI,        0x00000100
.equ RCC_AHB1Periph_GPIOJ,        0x00000200
.equ RCC_AHB1Periph_GPIOK,        0x00000400
.equ RCC_AHB1Periph_CRC,          0x00001000
.equ RCC_AHB1Periph_FLITF,        0x00008000
.equ RCC_AHB1Periph_SRAM1,        0x00010000
.equ RCC_AHB1Periph_SRAM2,        0x00020000
.equ RCC_AHB1Periph_BKPSRAM,      0x00040000
.equ RCC_AHB1Periph_SRAM3,        0x00080000
.equ RCC_AHB1Periph_CCMDATARAMEN, 0x00100000
.equ RCC_AHB1Periph_DMA1,         0x00200000
.equ RCC_AHB1Periph_DMA2,         0x00400000
.equ RCC_AHB1Periph_DMA2D,        0x00800000
.equ RCC_AHB1Periph_ETH_MAC,      0x02000000
.equ RCC_AHB1Periph_ETH_MAC_Tx,   0x04000000
.equ RCC_AHB1Periph_ETH_MAC_Rx,   0x08000000
.equ RCC_AHB1Periph_ETH_MAC_PTP,  0x10000000
.equ RCC_AHB1Periph_OTG_HS,       0x20000000
.equ RCC_AHB1Periph_OTG_HS_ULPI,  0x40000000
